// localization/en.ts
export default {
  common: {
    loading: 'Loading...',
    error: 'Error',
    retry: 'Retry',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    submit: 'Submit',
  },
  auth: {
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    username: 'Username',
    forgotPassword: 'Forgot Password?',
    resetPassword: 'Reset Password',
    noAccount: "Don't have an account?",
    alreadyAccount: 'Already have an account?',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    orContinueWith: 'Or continue with',
    passwordRequirements: 'Password must be at least 8 characters',
    emailInvalid: 'Please enter a valid email',
    emailRequired: 'Email is required',
    passwordRequired: 'Password is required',
    usernameRequired: 'Username is required',
    loginSuccess: 'Login successful',
    registerSuccess: 'Registration successful',
    logoutSuccess: 'Logout successful',
    loginError: 'Failed to login',
    registerError: 'Failed to register',
    logoutError: 'Failed to logout',
  },
  home: {
    welcome: 'Welcome to DUS Exam Prep',
    continue: 'Continue Learning',
    recentActivity: 'Recent Activity',
    upcomingExams: 'Upcoming Exams',
    practiceDuels: 'Practice Duels',
    studyStats: 'Study Statistics',
    findCourses: 'Find Courses',
    studyTime: 'Study Time',
    completedTopics: 'Completed Topics',
    achievements: 'Achievements',
    viewAll: 'View All',
  },
  courses: {
    myCourses: 'My Courses',
    allCourses: 'All Courses',
    courseDetails: 'Course Details',
    topics: 'Topics',
    progress: 'Progress',
    enroll: 'Enroll',
    continue: 'Continue',
    completed: 'Completed',
    startCourse: 'Start Course',
    courseCompletion: 'Course Completion',
    noCourses: 'No courses found',
    searchCourses: 'Search courses',
    filterCourses: 'Filter courses',
    sortBy: 'Sort by',
    difficulty: 'Difficulty',
    duration: 'Duration',
    rating: 'Rating',
    relevance: 'Relevance',
  },
  study: {
    studySession: 'Study Session',
    startStudy: 'Start Studying',
    endStudy: 'End Session',
    studyTime: 'Study Time',
    pauseStudy: 'Pause',
    resumeStudy: 'Resume',
    lessonComplete: 'Lesson Complete',
    topicComplete: 'Topic Complete',
    nextLesson: 'Next Lesson',
    previousLesson: 'Previous Lesson',
    reviewLesson: 'Review',
    takeNotes: 'Take Notes',
    markComplete: 'Mark as Complete',
    studyGoal: 'Study Goal',
    dailyGoal: 'Daily Goal',
    weeklyGoal: 'Weekly Goal',
    setGoal: 'Set Goal',
    goalAchieved: 'Goal Achieved!',
    timeStudied: 'Time Studied',
  },
  tests: {
    myTests: 'My Tests',
    allTests: 'All Tests',
    testResults: 'Test Results',
    startTest: 'Start Test',
    submitTest: 'Submit Test',
    timeLeft: 'Time Left',
    correctAnswers: 'Correct Answers',
    totalQuestions: 'Total Questions',
    score: 'Score',
    review: 'Review',
    retry: 'Retry',
    progress: 'Progress',
    testComplete: 'Test Complete',
    question: 'Question',
    of: 'of',
    next: 'Next',
    previous: 'Previous',
    difficulty: 'Difficulty',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    yourAnswer: 'Your Answer',
    correctAnswer: 'Correct Answer',
  },
  duels: {
    myDuels: 'My Duels',
    newDuel: 'New Duel',
    findOpponent: 'Find Opponent',
    inviteFriend: 'Invite Friend',
    acceptDuel: 'Accept Duel',
    declineDuel: 'Decline Duel',
    duelInProgress: 'Duel in Progress',
    duelCompleted: 'Duel Completed',
    duelCancelled: 'Duel Cancelled',
    winner: 'Winner',
    loser: 'Loser',
    draw: 'Draw',
    yourScore: 'Your Score',
    opponentScore: 'Opponent Score',
    duelHistory: 'Duel History',
    won: 'Won',
    lost: 'Lost',
    winRate: 'Win Rate',
    totalDuels: 'Total Duels',
    challengeFriend: 'Challenge Friend',
    randomOpponent: 'Random Opponent',
    waitingForOpponent: 'Waiting for Opponent',
    opponentFound: 'Opponent Found',
  },
  profile: {
    myProfile: 'My Profile',
    editProfile: 'Edit Profile',
    changePassword: 'Change Password',
    achievements: 'Achievements',
    statistics: 'Statistics',
    friends: 'Friends',
    settings: 'Settings',
    notifications: 'Notifications',
    language: 'Language',
    theme: 'Theme',
    about: 'About',
    help: 'Help',
    feedback: 'Feedback',
    logout: 'Logout',
    accountSettings: 'Account Settings',
    preferenceSettings: 'Preference Settings',
    appSettings: 'App Settings',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    systemDefault: 'System Default',
  },
  settings: {
    appSettings: 'App Settings',
    notifications: 'Notifications',
    sound: 'Sound',
    vibration: 'Vibration',
    language: 'Language',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    systemDefault: 'System Default',
    dataUsage: 'Data Usage',
    storageUsage: 'Storage Usage',
    clearCache: 'Clear Cache',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    about: 'About',
    version: 'Version',
    contactUs: 'Contact Us',
    feedback: 'Feedback',
    rateApp: 'Rate App',
    shareApp: 'Share App',
    deleteAccount: 'Delete Account',
  },
  errors: {
    generalError: 'Something went wrong. Please try again.',
    connectionError: 'Connection error. Please check your internet connection.',
    authError: 'Authentication error. Please login again.',
    serverError: 'Server error. Please try again later.',
    notFound: 'Not found',
    accessDenied: 'Access denied',
    sessionExpired: 'Session expired. Please login again.',
    tryAgain: 'Try Again',
    contactSupport: 'Contact Support',
  },
};
