// localization/tr.ts
export default {
  common: {
    loading: 'Yükleniyor...',
    error: 'Hata',
    retry: 'Tekrar Dene',
    cancel: 'İptal',
    save: 'Kaydet',
    delete: 'Sil',
    edit: 'Düzenle',
    submit: 'Gönder',
  },
  auth: {
    login: 'Giriş',
    register: 'Kayıt Ol',
    logout: 'Çıkış Yap',
    email: 'E-posta',
    password: 'Şifre',
    username: 'Kullanıcı Adı',
    forgotPassword: 'Şifreni mi Unuttun?',
    resetPassword: 'Şifreyi Sıfırla',
    noAccount: 'Hesabın yok mu?',
    alreadyAccount: 'Zaten hesabın var mı?',
    signIn: 'Giriş Yap',
    signUp: 'Kayıt Ol',
    orContinueWith: 'Veya şununla devam et',
    passwordRequirements: 'Şifre en az 8 karakter olmalıdır',
    emailInvalid: 'Lütfen geçerli bir e-posta adresi girin',
    emailRequired: 'E-posta gereklidir',
    passwordRequired: 'Şifre gereklidir',
    usernameRequired: 'Kullanıcı adı gereklidir',
    loginSuccess: 'Giriş başarılı',
    registerSuccess: 'Kayıt başarılı',
    logoutSuccess: 'Çıkış başarılı',
    loginError: 'Giriş yapılamadı',
    registerError: 'Kayıt olunamadı',
    logoutError: 'Çıkış yapılamadı',
  },
  home: {
    welcome: 'DUS Sınav Hazırlığına Hoş Geldiniz',
    continue: 'Öğrenmeye Devam Et',
    recentActivity: 'Son Aktiviteler',
    upcomingExams: 'Yaklaşan Sınavlar',
    practiceDuels: 'Pratik Düelloları',
    studyStats: 'Çalışma İstatistikleri',
    findCourses: 'Kursları Keşfet',
    studyTime: 'Çalışma Süresi',
    completedTopics: 'Tamamlanan Konular',
    achievements: 'Başarılar',
    viewAll: 'Tümünü Gör',
  },
  courses: {
    myCourses: 'Kurslarım',
    allCourses: 'Tüm Kurslar',
    courseDetails: 'Kurs Detayları',
    topics: 'Konular',
    progress: 'İlerleme',
    enroll: 'Kaydol',
    continue: 'Devam Et',
    completed: 'Tamamlandı',
    startCourse: 'Kursa Başla',
    courseCompletion: 'Kurs Tamamlama',
    noCourses: 'Kurs bulunamadı',
    searchCourses: 'Kursları ara',
    filterCourses: 'Kursları filtrele',
    sortBy: 'Sırala',
    difficulty: 'Zorluk',
    duration: 'Süre',
    rating: 'Değerlendirme',
    relevance: 'İlgililik',
  },
  study: {
    studySession: 'Çalışma Oturumu',
    startStudy: 'Çalışmaya Başla',
    endStudy: 'Çalışmayı Bitir',
    studyTime: 'Çalışma Süresi',
    pauseStudy: 'Duraklat',
    resumeStudy: 'Devam Et',
    lessonComplete: 'Ders Tamamlandı',
    topicComplete: 'Konu Tamamlandı',
    nextLesson: 'Sonraki Ders',
    previousLesson: 'Önceki Ders',
    reviewLesson: 'Gözden Geçir',
    takeNotes: 'Not Al',
    markComplete: 'Tamamlandı Olarak İşaretle',
    studyGoal: 'Çalışma Hedefi',
    dailyGoal: 'Günlük Hedef',
    weeklyGoal: 'Haftalık Hedef',
    setGoal: 'Hedef Belirle',
    goalAchieved: 'Hedefe Ulaşıldı!',
    timeStudied: 'Çalışılan Süre',
  },
  tests: {
    myTests: 'Testlerim',
    allTests: 'Tüm Testler',
    testResults: 'Test Sonuçları',
    startTest: 'Teste Başla',
    submitTest: 'Testi Gönder',
    timeLeft: 'Kalan Süre',
    correctAnswers: 'Doğru Cevaplar',
    totalQuestions: 'Toplam Soru',
    score: 'Puan',
    review: 'Gözden Geçir',
    retry: 'Tekrar Dene',
    progress: 'İlerleme',
    testComplete: 'Test Tamamlandı',
    question: 'Soru',
    of: '/',
    next: 'Sonraki',
    previous: 'Önceki',
    difficulty: 'Zorluk',
    easy: 'Kolay',
    medium: 'Orta',
    hard: 'Zor',
    yourAnswer: 'Cevabınız',
    correctAnswer: 'Doğru Cevap',
  },
  duels: {
    myDuels: 'Düellolarım',
    newDuel: 'Yeni Düello',
    findOpponent: 'Rakip Bul',
    inviteFriend: 'Arkadaşını Davet Et',
    acceptDuel: 'Düelloyu Kabul Et',
    declineDuel: 'Düelloyu Reddet',
    duelInProgress: 'Düello Devam Ediyor',
    duelCompleted: 'Düello Tamamlandı',
    duelCancelled: 'Düello İptal Edildi',
    winner: 'Kazanan',
    loser: 'Kaybeden',
    draw: 'Berabere',
    yourScore: 'Puanınız',
    opponentScore: 'Rakip Puanı',
    duelHistory: 'Düello Geçmişi',
    won: 'Kazanılan',
    lost: 'Kaybedilen',
    winRate: 'Kazanma Oranı',
    totalDuels: 'Toplam Düello',
    challengeFriend: 'Arkadaşına Meydan Oku',
    randomOpponent: 'Rastgele Rakip',
    waitingForOpponent: 'Rakip Bekleniyor',
    opponentFound: 'Rakip Bulundu',
  },
  profile: {
    myProfile: 'Profilim',
    editProfile: 'Profili Düzenle',
    changePassword: 'Şifre Değiştir',
    achievements: 'Başarılar',
    statistics: 'İstatistikler',
    friends: 'Arkadaşlar',
    settings: 'Ayarlar',
    notifications: 'Bildirimler',
    language: 'Dil',
    theme: 'Tema',
    about: 'Hakkında',
    help: 'Yardım',
    feedback: 'Geri Bildirim',
    logout: 'Çıkış Yap',
    accountSettings: 'Hesap Ayarları',
    preferenceSettings: 'Tercih Ayarları',
    appSettings: 'Uygulama Ayarları',
    darkMode: 'Karanlık Mod',
    lightMode: 'Aydınlık Mod',
    systemDefault: 'Sistem Varsayılanı',
  },
  settings: {
    appSettings: 'Uygulama Ayarları',
    notifications: 'Bildirimler',
    sound: 'Ses',
    vibration: 'Titreşim',
    language: 'Dil',
    theme: 'Tema',
    darkMode: 'Karanlık Mod',
    lightMode: 'Aydınlık Mod',
    systemDefault: 'Sistem Varsayılanı',
    dataUsage: 'Veri Kullanımı',
    storageUsage: 'Depolama Kullanımı',
    clearCache: 'Önbelleği Temizle',
    privacyPolicy: 'Gizlilik Politikası',
    termsOfService: 'Kullanım Şartları',
    about: 'Hakkında',
    version: 'Sürüm',
    contactUs: 'Bize Ulaşın',
    feedback: 'Geri Bildirim',
    rateApp: 'Uygulamayı Değerlendir',
    shareApp: 'Uygulamayı Paylaş',
    deleteAccount: 'Hesabı Sil',
  },
  errors: {
    generalError: 'Bir şeyler yanlış gitti. Lütfen tekrar deneyin.',
    connectionError:
      'Bağlantı hatası. Lütfen internet bağlantınızı kontrol edin.',
    authError: 'Kimlik doğrulama hatası. Lütfen tekrar giriş yapın.',
    serverError: 'Sunucu hatası. Lütfen daha sonra tekrar deneyin.',
    notFound: 'Bulunamadı',
    accessDenied: 'Erişim reddedildi',
    sessionExpired: 'Oturum süresi doldu. Lütfen tekrar giriş yapın.',
    tryAgain: 'Tekrar Dene',
    contactSupport: 'Destek Ekibi ile İletişime Geç',
  },
};
